### PR TITLE
added tc-auth

### PR DESCRIPTION
**Pull request by veshu**

### CODE REVIEW

**Comment by zsudraco** [comment]
The functionalities work.
It is suggested to do the following testing enhancements:

1.
the back end unit tests are not updated, and they fail, better to update them to fit new model

2.
the postman collection is not updated, better to update them to fit new model

**Comment by callmekatootie** [comment]
@veshu Please see reviewer comments above. Can you kindly fix it today

**Comment by veshu** [comment]
@callmekatootie @zsudraco Above points are now fixed. Thanks

**Comment by zsudraco** [comment]
They are ok now.

**Comment by callmekatootie** [comment]
@cwdcwd Auth in Vorbote is already existing in `develop` branch. I am guessing we need to carry out additional steps in heroku for smooth deployment?

**Comment by cwdcwd** [comment]
@callmekatootie something's not quite right in the heroku instance with this:
image

**Pull request merged**
